### PR TITLE
removed Slack notification and Properties on Jenkins file

### PR DESCRIPTION
**Pull request by AVandana-OSI**
Clean up by removing the echo and print statements from build.gradle and Jenkins file, Also slack notification. Added Triggers too as a part of properties.

### CODE REVIEW

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by mgrmax** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Comment by SashaKyz** [comment]
retest this please

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by SashaKyz** [comment]
Retest this please

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by AVandana-OSI** [comment]
recheck this please

**Pull request merged**
